#!/bin/fish
set i 1
while test $i -le (count $argv)
	set arg $argv[$i]
	if not test "$bin"; and rg -q -e "name='$arg" Cargo.toml
		set bin $arg
	else if rg -q -e "$arg=" Cargo.toml
		set -a features $arg
	else if test -e $arg/Cargo.toml
		cd $arg
	else if test $arg = '--release'
		set -a args $arg
	else
		break
	end
	set i (math $i+1)
end
test "$bin" && set bin "--bin $bin"
test "$features" && set features --features (string join , $features)
set -p args $bin $features
test "$args" && echo $args
set run_args $argv[$i..]
test "$run_args" && echo $run_args >&2
