#!/bin/fish
set cargo_args (cargo_args $argv 2>/dev/null)
#cargo -Z namespaced-features check (string split ' ' -- $cargo_args)
CARGO_BUILD_RUSTC=/opt/rust/toolchains/beta-x86_64-unknown-linux-gnu/bin/rustc RUSTC_BOOTSTRAP=1 cargo watch --no-gitignore -q -s "diagnostic-kate -Zallow-features=edition2021,trait_alias,associated_type_bounds,const_fn_trait_bound,array_zip,once_cell,async_closure,backtrace $cargo_args" && rm -I Cargo.lock
# array_zip: vector operations [image]
# once_cell: image sRGB
# async_closure: ui app dispatch queue
# backtrace: anyhow cfg_attr backtrace mischecks
