#!/bin/sh
echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
cd /sys/devices/system/cpu && for core in policy*; sudo sh -c "echo power > $core/energy_performance_preference"; end
sudo x86_energy_perf_policy power
echo 1 > /sys/devices/system/cpu/intel_pstate/max_perf_pct
sudo dell-bios-fan-control 0
sudo eselect rc restart i8kmon
cat /sys/devices/system/cpu/intel_pstate/max_perf_pct
rg MHz /proc/cpuinfo
