#!/bin/env fish
set path $argv[1]
test $path || set path .
test (realpath $path) != $HOME || exit
set exclude --exclude=.git --exclude=target --exclude=Cargo.lock --exclude=build --exclude=debug --exclude '.*.kate-swp'
test (du -s $exclude $path | cut -f1) -le 300000 || exit
rg -v 'm100 ssh-ed25519 ' ~/.ssh/known_hosts | sponge ~/.ssh/known_hosts
set USER (string join '' (string sub -l 1 (string split '.' $USER)[1]) (string sub -l 7 (string split '.' $USER)[2]))
set path (realpath --relative-base=$HOME $path)
rsync -v -t -z -r -u $exclude ~/$path/ $USER@m100:$path $argv[2..]
