#!/bin/fish
for file in $argv
set RES (ffprobe $file 2>&1 | rg Video | rg '[0-9]+x[0-9]+' -o)
set FPS (ffprobe $file 2>&1 | rg '([0-9]+.?[0-9]?)[0-9]* fps' -o -r '$1')
set FPS (swaymsg -t get_outputs -p | rg $FPS'[0-9]*' -o -m 1)
echo $RES $FPS
swaymsg output HDMI-A-1 mode "$RES"@"$FPS"Hz
killall wlsunset
mpv $file
end
